kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - docker build . --tag registry.mmskl.net/tkfmh_mmskl_net
    - docker push registry.mmskl.net/tkfmh_mmskl_net 
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: run
  image: docker/compose
  commands:
    - docker compose up -d
  volume:
    - /var/run/docker.sock:/var/run/docker.sock

settings:
  registry: registry.mmskl.net
  repo: tkfmh_mmskl_net
  username:
    from_secret: registry_username
  password:
    from_secret: registry_password



volumes:
- name: docker
  host:
    path: /var/run/docker.sock
