kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  commands:
    - docker build . --tag registry.mmskl.net/tkfmh_mmskl_net
    - docker push registry.mmskl.net/tkfmh_mmskl_net 
  volumes:
  - name: docker
    path: /var/run/docker.sock
  secrets: [ registry_username, registry_password ]
- name: run
  image: docker/compose
  commands:
    - docker compose up -d
  volume:
    - /var/run/docker.sock




volumes:
- name: docker
  host:
    path: /var/run/docker.sock
