kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - docker build . --tag registry.mmskl.net/tkfmh_mmskl_net
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DEBUG: false

- name: push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.mmskl.net/tkfmh_mmskl_net
    registry: registry.mmskl.net

- name: run
  image: docker/compose
  commands:
    - docker-compose -p tkfmh_mmskl_net up -d
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
