kind: pipeline
name: default

steps:
- name: push
  image: plugins/docker
  commands:
    - docker build . --tag registry.mmskl.net/tkfmh_mmskl_net
    - echo "$$DOCKER_PASSWORD" | docker login --username "$$DOCKER_USER" --password-stdin
    - docker push registry.mmskl.net/tkfmh_mmskl_net
  environment:
    DEBUG: false
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock

  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.mmskl.net/tkfmh_mmskl_net
    registry: registry.mmskl.net
    purge: false
    dry_run: false

- name: run
  image: docker/compose
  commands:
    - docker-compose -p tkfmh_mmskl_net up -d
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
