kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - docker build . --tag registry.mmskl.net/tkfmh_mmskl_net
    - docker login --username="$${DOCKER_USERNAME}" --password="$${DOCKER_PASSWORD}" registry.mmskl.net
    - docker push registry.mmskl.net/tkfmh_mmskl_net 
  secrets: [ docker_username, docker_password ]
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: run
  image: docker/compose
  commands:
    - docker compose up -d
  volume:
    - /var/run/docker.sock


image_pull_secrets:
- dockerconfigjson


volumes:
- name: docker
  host:
    path: /var/run/docker.sock
