kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - docker build . -t tkfmhack
    - docker save tkfmhack > /images/tkfmhack.tar
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/admin/images:/images"
