version: '3'
services:
  app:
    image: registry.mmskl.net/tkfmh_mmskl_net
    container_name: "tokfmhack_app"
    restart: unless-stopped
    volumes:
        - tkfmhack_volume:/opt/Tokfmhack/data
    ports:
        - "8088:5000"
    environment:
     - DEBUG=false

volumes:
  tkfmhack_volume:
